### ISSUE TITLE
Faith of functions shadowed in razzo

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#116]
When I start razzo, I get:

```
> library(razzo)

Attaching package: ‘razzo’

The following objects are masked from ‘package:pirouette’:

    combine_brts_and_topology, create_bd_tree
```

What is the faith of razzo::combine_brts_and_topology and razzo::create_bd_tree?

If these can be deleted, go ahead and hit it :+1:

**Comment by Giappo** [comment]
I don't understand what you are referring to.
If I look into razzo [namespace](https://github.com/richelbilderbeek/razzo/blob/master/NAMESPACE) I can't find any of these functions. If I do ctrl+shift+f into razzo's R project I get no references to these functions. I migrated into [pirouette](https://github.com/richelbilderbeek/pirouette/blob/master/NAMESPACE) as I think they can be useful for the general purpose. Are you sure it isn't just a problem due to not updating packages?

**Comment by richelbilderbeek** [comment]
Yes, problem was at my side. Sorry for the noise.

Good to remember how it feels to forget to merge again :cloud_with_rain:
