### ISSUE TITLE
'create_stunning_tree' fails for n_taxa != 5

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#129]
`create_stunning_tree` is the function to create the most stunning trees ever to have been created in living memory.

It was intended to be used in the article only, but then someone came and started to use that function. For 5 taxa, it works like a breeze:

```r
test_that("default use must be silent", {

  expect_silent(create_stunning_tree())
})
```

For any other number of taxa, there are errors:

```r
test_that("number of taxa and tips must match", {

  skip("Issue 129, #129")
  n_taxa <- 3
  phylo <- create_stunning_tree(n_taxa = n_taxa)
})
```

**Comment by richelbilderbeek** [comment]
I think @Giappo would like to fix this :+1:

**Comment by Giappo** [comment]
Now it's possible to create tree with different n_taxa.
The calculation, though, relies on an approximation on the likelihood. The precision on the approximation depends (linearly) on the number of taxa so big trees can require more time.
I also improved the tip naming allowing for labels that  exceed 26.
It should be fine. If you think it's okay @richelbilderbeek , close the issue. Otherwise tell me if you desire something more.

**Comment by richelbilderbeek** [comment]
This was what I wanted indeed!

The result does look rather regular, but well, that is what it is :-)

![2019-02-22-072144_1202x925_scrot](https://user-images.githubusercontent.com/2098230/53223721-89f1af00-3672-11e9-9510-e6643a2036dc.png)
