### ISSUE TITLE
Add 'create_ideal_tree' function stub

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#131]
In the manuscript, ~~I'd like to write~~ I've written:

```r
phylogeny <- create_ideal_tree(n_taxa = 5, crown_age = 10)
```

Create that function. Sure, we need to settle on what an ideal tree is (#127), but using the new `create_stunning_tree` for now would be a good stub.

`create_ideal_tree` will once need some defaults, e.g. a tree prior name (by default, this is `yule`, as BEAST2 uses Yule as well), but go as far as you'd like :+1:

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy this one :rainbow:

**Comment by Giappo** [comment]
The function should be ready. I didn't add any "tree_prior_name" parameters, even though the likelihood is for a tree with no extinction events.
Do you also want a version with mu > 0? In that case I would use Nee's likelihood. However, I would need an additional information because the relation:
r <- (log(n_taxa) - log(n_0)) / t_0 # r = lambda - mu
can fix only one parameter.
An option could be to provide lambda and/or mu as input(s). For the twin, for example, this could be done using the parameters inferred from the original distribution.
If the tree is not a twin we would need to provide an additional information, I dunno how.

**Comment by richelbilderbeek** [comment]
> Do you also want a version with mu > 0?

Yes, that would be helpful!

> However, I would need an additional information

I feel one does not need it (I feel an ideal tree has the most expected diversification rate (mu + lambda)), but you are the expert here. Would an added arbitrary constraint like `lambda + mu = 1` resolve the problem?

**Comment by Giappo** [comment]
We have two degrees of freedom so we need two independent equations so, yes, lambda + mu = 1 will provide a second (yet arbitrary) constraint.
If my > 0 species will die at some point. Do we want to remove the dead ends and just leave the reconstructed tree, right?

**Comment by richelbilderbeek** [comment]
AFAICS this is done, as the function is there.

```r
#' Create an "ideal" tree
#' @inheritParams default_params_doc
#' @export
#' @author Richel J.C. Bilderbeek, Giovanni Laudanno
create_ideal_tree <- function(
  n_taxa,
  crown_age,
  n_0 = 2,
  ideal_method = "stunning"
) {
  if (!(ideal_method %in% get_ideal_methods())) {
    stop("This 'ideal_method' is not implemented")
  }
  if (ideal_method == "stunning") {
    ideal_tree <- create_stunning_tree(
      t_0 = crown_age,
      n_taxa = n_taxa,
      n_0 = n_0
    )
  }
  testit::assert(beautier::is_phylo(ideal_tree))
  ideal_tree
}
```

@Giappo: can I close it, or do you have some more ideas up in your sleeves? If no, go ahead and close it :+1:

**Comment by richelbilderbeek** [comment]
Will move this Issue to 'To Do', as I feel that is the better spot for it :rainbow:

**Comment by Giappo** [comment]
As I said in #133 we cannot use the "stunning" method. We don't need an "ideal" tree, though, so it's probably fine.
If you're ok with that I'd suggest to close these two issues and open a new one to remove the stuff we don't use.
