### ISSUE TITLE
Add 'stunning' as 'create_twinning_params' method 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#133]
Currenty, `create_twinning_params` has some methods to generate the twin tree. As a big fan of the `create_stunning_tree` function (and especially its algorithm), I'd enjoy this method to be added.

It will also help to settle on what an ideal tree may be (#127)

**Comment by richelbilderbeek** [comment]
I think @Giappo would like this one :+1:

**Comment by Giappo** [comment]
@richelbilderbeek currently "create_stunning_tree" doesn't require inputs like lambda and mu, as it sets mu = 0 and lambda = (log(n_taxa) - log(n_0)) / t_0
When we calculate a twin tree, though, we actually have lambda and mu estimated from the phylogeny.
The method per se should not allow to set a mu != 0, because this would mean to change the likelihood, which is quite a simple one, in this form.
We can still use the lambda, as we would do when we use twin_model == yule.
What do you think?

**Comment by richelbilderbeek** [comment]
I know for sure I enjoy the interface of `create_stunning_tree`!

But I feel this is more about twinning (I hope I understood your points well, else please correct me). I think `create_stunning_tree` is a valid method to generate a twin -indeed- Yule tree. I'd find a rename to `create_stunning_yule_tree` acceptable, opening up an avenue for adding `create_stunning_bd_tree`. 

But I also remember that stunning trees looked rather ... non-stunning ... for more than ten taxa. I have a vague idea we'd not expand on this tree generation method.

Helpful? If not, please help me out :+1:

**Comment by richelbilderbeek** [comment]
Will move this Issue to 'To Do', as I feel that is the better spot for it :rainbow:

**Comment by Giappo** [comment]
Hi Richel,

So I checked better and turned out that we cannot use this method. So no stunning tree, but fortunately we don't need it because we decided to use the "random_tree" method, which is also much simpler.

**Comment by Giappo** [comment]
Depends on #164
