### ISSUE TITLE
razzo: fix get_data_paths

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#155]
This test fails:

```
context("get_data_paths")

test_that("use", {
  skip("")
  all_paths <- get_data_paths(get_path("razzo_project"))
  expect_true(
    length(all_paths) > 0
  )
  expect_true(
   is.character(all_paths)
  )
})
```

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy fixing his own work :+1:

**Comment by Giappo** [comment]
Hi Richel,

The function does not work because we used to set up razzo in such a way everything was done in a specific project folder given by the variable "project_folder_name".
The way pirouette works instead is to put all the files in a temporary folder.
I think the idea of a project folder is a good system. I also think that if we want to keep it we need to implement it in pirouette, in the first place. This has to be done, I think, changing how create_pir_params, allowing the user to specify a directory where to store everything. This could, probably, easily become part of the misc_params

**Comment by richelbilderbeek** [comment]
> The function does not work because we used to set up razzo in such a way everything was done in a specific project folder given by the variable "project_folder_name".
> The way pirouette works instead is to put all the files in a temporary folder.

Good thinking, but incorrect: *by default* pirouette stores files in temp locations. But in `razzo::create_parameters_files` I set the path of all these files, exactly like you suggested :sunglasses: !

Check it out, it is great :+1:

**Comment by Giappo** [comment]
In its previous reincarnation razzo used to save data into razzo/inst/extdata/razzo_project/data.
Now it saves into razzo/data.
Do you confirm that we want to discard the previous setting in favor of this new one?

**Comment by richelbilderbeek** [comment]
razzo_project does follow the file structure we decided upon together. Go ahead and modify the inst/extdata folder :+1:

**Comment by richelbilderbeek** [comment]
Will move this Issue to 'To Do', as I feel that is the better spot for it :rainbow:

**Comment by Giappo** [comment]
Everything seems to work quite fine. I'll close this issue.
