### ISSUE TITLE
pirouette: improve pir_plot 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#175]
Currently, it is not show which models were the generative or best candidate ones:

![figure_example_3](https://user-images.githubusercontent.com/2098230/53789308-69540f80-3f24-11e9-994f-dfa7f19a588a.png)

It would be better to name the site model, clock model and tree prior somewhere in the figure.

@Giappo: this is an Issue you could do halfway: if you label the generative model's result and its twin, it will be way easier for me to do so with the candidates :rain'

**Comment by richelbilderbeek** [comment]
Wishlist:

![2019-03-15-122125_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/54428538-1ba68680-471e-11e9-892d-80f0528970c0.png)

**Comment by richelbilderbeek** [comment]
@Giappo: may I assign you this is Issue? I think my picture is clear enough to indicate exactly what I want. Feel free to do even better than my suggestions :+1: 

Will assume @Giappo say yes, because he is like that :sunglasses:

**Comment by Giappo** [comment]
Ok @richelbilderbeek this one is complicated.
I am about to push a version which imho looks definitely better than the old ones. I still have a doubt, though, because in this way we will have a discrete x value for every possible inference model, which is not what we want...
Give a look on how it is and let's think of a better solution.
Ah, I really think that we should stick to this facet/fill (aka "model_type" and "tree" in our terms) structure as it is more logical, I think.

Waiting for your opinion.

**Comment by richelbilderbeek** [comment]
Cool, will take a look tomorrow :+1:

**Comment by richelbilderbeek** [comment]
When doing this:

```
    pir_plot(
      create_pir_run_test_output(
        add_twin = TRUE,
        add_best = TRUE
      )
    )
```

I see it has improved heavily! All this is needed is to remove unusued values:

![2019-03-19-072334_1202x930_scrot](https://user-images.githubusercontent.com/2098230/54584635-31ff5b80-4a18-11e9-898a-c5263448b723.png)

**Comment by richelbilderbeek** [comment]
Fixed:

![2019-03-19-074754_1202x930_scrot](https://user-images.githubusercontent.com/2098230/54585801-6d4f5980-4a1b-11e9-8d71-1c5f5745da49.png)
