### ISSUE TITLE
razzo must use the new babette interface

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#352]
In the old days, one would write:

```r
bbt_run_from_model(
  beast2_options = create_beast2_options(
    output_log_filename = "out.log",
    output_trees_filenames = "out.trees
  )
)
```

These two files, however, have been an inherent part of a `beautier` MCMC object.

Nowadays one writes:

```r
bbt_run_from_model(
  inference_model = create_inference_model(
    mcmc = create_mcmc(
      tracelog = create_tracelog(
        filename = "out.log"
      ),
      treelog = create_treelog(
        filenames = "out.trees
      )
    )
  )
)
```

Make razzo use the new interface.

**Comment by Giappo** [comment]
@richelbilderbeek 
Ok, so I gave a look into it and I noticed that there are many tests that fail. This is due to the fact that many razzo functions that retrieve data from folders, e.g all the "collect_*" ones, cannot do it properly because the data, and therefore the parameters, have not been yet regenerated in order to match the new style.
Can you regenerate the data (even a small dataset) present in the "extdata" folder in order to make all the tests that are not strictly involved with this issue passing?

**Comment by Giappo** [comment]
> @richelbilderbeek
> Ok, so I gave a look into it and I noticed that there are many tests that fail. This is due to the fact that many razzo functions that retrieve data from folders, e.g all the "collect_*" ones, cannot do it properly because the data, and therefore the parameters, have not been yet regenerated in order to match the new style.
> Can you regenerate the data (even a small dataset) present in the "extdata" folder in order to make all the tests that are not strictly involved with this issue passing?

Question: can this be done modifying the function "create_test_parameters_files"?

**Comment by richelbilderbeek** [comment]
Cool, thanks for the help!

> Can you regenerate the data (even a small dataset) present in the "extdata" folder in order to make all the tests that are not strictly involved with this issue passing?

I will, if you don't beat me first (see below) :rainbow: 

> Question: can this be done modifying the function "create_test_parameters_files"?

I think so. I usually use the script `scripts/regen_data`, but if you get it to work, go ahead :+1:

**Comment by Giappo** [comment]
Ok @richelbilderbeek , sorry but I need more information to work with this and without relying on the general test structure unfortunately I am having hard times even understanding (precisely) the problem.

At the current state this is the default configuration for "beautier::create_mcmc"

`
create_mcmc(chain_length = 1e+07, store_every = -1, pre_burnin = 0,
  n_init_attempts = 10, sample_from_prior = FALSE,
  tracelog = create_tracelog(), screenlog = create_screenlog(),
  treelog = create_treelog())
`

Question: can we solve all our problems simply changing it to the following?

`
create_mcmc(
  chain_length = 1e+07, 
  store_every = -1, 
  pre_burnin = 0,
  n_init_attempts = 10, 
  sample_from_prior = FALSE,
  tracelog = create_tracelog(filename = "out.log"), 
  screenlog = create_screenlog(),
  treelog = create_treelog(filenames = "out.trees)
)
`

If it's not I suppose it could be because we need instead specific filenames to be defined at a specific level in the structure (at the babette level, at the pirouette level or at the razzo/raket level). Is it so? If yes what names do we want to use and at what level?

**Comment by richelbilderbeek** [comment]
> Question: can we solve all our problems simply changing it to the following?

Sadly not, as the filenames we use in `razzo` have a more complex structure than just `out.log`.

> If it's not I suppose it could be because we need instead specific filenames to be defined at a specific level in the structure (at the babette level, at the pirouette level or at the razzo/raket level). Is it so? 

Yes, they are specified at the `razzo` level, in `create_razzo_params_files` (or a similar name).

> If yes what names do we want to use and at what level?

We want to use the same names as we used earlier.

In the current functions, we find code like this:

```r
create_beast2_options(
  output_log_filename = "something_complex.log",
  output_trees_filenames = "something_complex.trees
)
```

These filenames are now stored at:

```r
create_mcmc(
  tracelog = create_tracelog(
    filename = "something_complex.log"
  ),
  treelog = create_treelog(
    filenames = "something_complex.trees
  )
)
```

I hope that helps. 

I understand it is hard to program 'in the dark'. Just see how far you get, I'll continue from there :+1:

**Comment by Giappo** [comment]
Hi @richelbilderbeek 
I have the feeling that I might have solved the problem. It feels a bit unsafe to assess this "in the darkness" but we'll see when the tests are back.
The only thing I don't know how to deal with is the "get_razzo_mcmc" function, as that one is used in contexts where the model_type and the folder_name are not specified...

**Comment by richelbilderbeek** [comment]
Cool, thanks! I will take over from there :+1: 

Don't forget #351, which is about the same for the `peregrine` package :rainbow:
